### ISSUE TITLE
Atualização do Heap

### ISSUE THREAD

**Issue by MMaestrelliLeobons** [brunocalou/graph-theory-js#4]
Nao e possível atualizar a prioridade de um elemento na arvore binaria depois dele ter sido adicionado na estrutura.
A melhor solução para o caso seria uma função que recebe o índice e o novo peso do elemento e atualiza a prioridade na estrutura.

**Comment by brunocalou** [comment]
Resolvido --> 5086936591c9812fc11fba9d403db555cc109f03
função changeElement recebe o elemento a ser substituído e o novo elemento
